name: Build and Release
on:
  push:
    branches:
      - master

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18' # Specify your Node.js version

    - name: Install dependencies
      run: yarn install

    - name: Build React app
      run: yarn run build
        
    - name: Semantic Release
      uses: semantic-release/semantic-release@17.4.7
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      with:
        plugins: |
          "@semantic-release/commit-analyzer",
          "@semantic-release/release-notes-generator",
          "@semantic-release/changelog",
          "@semantic-release/npm",
          ["@semantic-release/git", {
            "assets": ["dist/**", "package.json"],
            "message": "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
          }]

    - name: Get next version
      uses: reecetech/version-increment@2023.10.2
      id: version
      with:
        scheme: semver
        increment: patch