name: Tests
on:
  push:
    branches:
      - master

permissions:
  contents: read # for checkout

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      - name: Install dependencies
        run: yarn install
      - name: Run tests
        run: yarn run test